config/routes.rb
Rails.application.routes.draw do

  resources :about_pages

  resources :pages

  resources :friendships

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :resorts

  resources :reviews

  resources :room_photos

  resources :rooms

  resources :photos

  resources :services

  resources :hotels

  resources :users

  resources :messages

  resources :events

  get 'profile' => 'users#profile', :as => 'user_profile'

  root 'pages#index'
  get 'payment' => 'pages#payment', as: 'payment'
  get 'not_found' => 'pages#not_found', as: 'not_found'

  namespace :manage do
    resources :manage_hotels
    get 'manage_hotels/:id/upload' => "manage_hotels#upload", :as => 'manage_hotels_upload'
    get 'manage_hotels/:id/rooms' => "manage_hotels#rooms", :as => 'manage_hotels_rooms'

    resources :manage_services
    resources :manage_resorts
    resources :manage_users
    resources :manage_about_pages
    resources :manage_pages
  end

  resources :hotels do
    resources :rooms
    resources :reviews
  end

end

app/models/about_page.rb
class AboutPage < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	belongs_to :resort
	has_many :hotel_services
	has_many :services, through: :hotel_services
	has_many :photos
	has_many :rooms
	has_many :reviews
	accepts_nested_attributes_for :photos, :allow_destroy => true

	has_attached_file :image, :styles => { :original => "900x600>", :square => "200x200#", :rectangle => "285x146#", :slider => "240x160#", :thumbnail => "70x70#" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/hotel_service.rb
class HotelService < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :service
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :hotel

	has_attached_file :image, :styles => { :original => '900x600#', :hotel => "155x96#", :hotel_gallery => "140x105#", :room_big => "300x200#", :room_square => "200x200#", :room_thumb => "96x96#" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/resort.rb
class Resort < ActiveRecord::Base
	has_many :hotels

	has_attached_file :image, :styles => { :original => "900x600>", :large => "1280x400#", :square => "150x150#" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :hotel
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :room
	has_many :room_photos
	accepts_nested_attributes_for :room_photos, :allow_destroy => true
end

app/models/room_photo.rb
class RoomPhoto < ActiveRecord::Base
	belongs_to :room

	has_attached_file :image, :styles => { :original => '900x600#', :room_big => "300x200#", :room_square => "200x200#", :room_thumb => "96x96#" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :hotel_services
	has_many :hotels, through: :hotel_services
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many :events

  
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  before_create :set_default_role

  validates :email, presence: true
  validates :password, presence: true, length: {minimum: 5, maximum: 120}, on: :create
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_admin_bar.html.erb
<% if user_signed_in? %>
	<div class="admin-bar">
		<ul class="list-inline">
			<li><%=link_to 'На сайт', root_path %></li>
			<li><%=link_to 'Личный кабинет', user_profile_path(current_user) %></li>
			<% if current_user.role_id == 6 %>
			<li><%=link_to 'Управление отелями', manage_manage_hotels_path %></li>
			<li><%=link_to 'Опции инфраструктуры', manage_manage_services_path %></li>
			<li><%=link_to 'Управление курортами', manage_manage_resorts_path %></li>
			<% end %>
			<% if current_user.role_id == 4 %>
			<li><%=link_to 'Управление отелями', manage_manage_hotels_path %></li>
			<li><%=link_to 'Опции инфраструктуры', manage_manage_services_path %></li>
			<li><%=link_to 'Управление курортами', manage_manage_resorts_path %></li>
			<% end %>
			<% if current_user.role_id == 6 %>
			<li><%=link_to 'Управление пользователями', manage_manage_users_path %></li>
			<li><%=link_to 'Управление страницами компании', manage_manage_about_pages_path %></li>
			<li><%=link_to 'Управление статическими страницами', manage_manage_pages_path %></li>
			<% end %>
			
			<li class="pull-right"><%= current_user.email %> | <%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin_bar' %>

<div class="container header">
	<div class="row">
		<div class="col-lg-5 header-logo">
			<a href="/"><img alt="Header logo" src="/assets/header-logo.svg" /></a>
		</div>
		<div class="col-lg-4 header-buttons">
			<ul class="list-inline">
				<li class="header-region">Регион:</li>
				<li>
					<div class="dropdown">
						<button class="btn btn-default btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
							Санкт-Петербург
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
							<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Москва</a></li>
							<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Краснодар</a></li>
							<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Минск</a></li>
						</ul>
					</div>
				</li>
			</ul>
			<p>
				<a type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#myModal">
					<span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> Обратный звонок
				</a>
	
					
				<% if user_signed_in? %>
					<%= link_to "/profile", :class=>"btn btn-info btn-xs", :method => :get do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>Личный кабинет
					<% end %>
				<% else %>
					<%= link_to "/users/sign_in", :class=>"btn btn-info btn-xs", :method => :get do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>Личный кабинет
					<% end %>
				<% end %>
			</p>
		</div>
		<div class="col-lg-3 header-phone">
			<div class="header-phone-number">+7 (499) 704-21-11
				<p>ежедневно с 9-00 до 21-00</p></div>
			</div>
		</div>
	</div>
</div>
<div class="main-menu">
	<nav class="navbar navbar-default">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><%= link_to 'Главная', root_path %></li>
				<li><%= link_to 'О компании', about_pages_path %></li>
				<% Page.all.each do |page| %>
					<li><%= link_to page.name, page %></li>
				<% end %>
				<li><%= link_to 'Оплата тура', payment_path %></li>
			</ul>
		</div><!-- /.container-fluid -->
	</nav>
</div>
<%= yield %>
<div class="container footer">
	<div class="footer-content">
		<div class="footer-logo">
			<img src="/assets/footer-logo.png">
		</div>
		<div class="footer-copyright">
			<p>© 2014 Центр Онлайн Бронирования</p>
		</div>
		<div class="footer-counters">
			<ul class="list-inline">
				<li><img src="http://placehold.it/102x46"></li>
				<li><img src="http://placehold.it/102x46"></li>
			</ul>
		</div>
		<div class="footer-social">
			<script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script><div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="small" data-yashareQuickServices="vkontakte,facebook,odnoklassniki,gplus" data-yashareTheme="counter"></div>
		</div>

	</div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel">Обратный звонок</h4>
			</div>
			<div class="modal-body">
				<form role="form">
					<div class="form-group">
						<label>Ваше имя</label>
						<input type="text" class="form-control" placeholder="Ваше имя">
					</div>
					<div class="form-group">
						<label>Номер телефона</label>
						<input type="text" class="form-control" placeholder="+7(___)___-__-__">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-info">Перезвоните мне</button>
			</div>
		</div>
	</div>
</div>

</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin_bar' %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>